const demo = {pvPower:1842.6,batterySoc:86.4,batteryChargePower:1284.3,homeLoad:1150.0,gridPower:350.0,batteryDailyKwh:8.6,batteryMonthKwh:238.6,batteryTotalKwh:1522.6,weather:"cloudy",night:false};
function fmt(v,d=1){return Number(v||0).toFixed(d).replace(".",",");}
function euro(v){return Number(v||0).toFixed(2).replace(".",",")+" €";}
function text(id,value){const el=document.getElementById(id);if(el)el.innerText=value;}
function html(id,value){const el=document.getElementById(id);if(el)el.innerHTML=value;}
function updateTime(){const days=["So","Mo","Di","Mi","Do","Fr","Sa"];const now=new Date();const day=days[now.getDay()];const date=now.toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"});const time=now.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit",second:"2-digit"});text("dateLine",`${day} · ${date} · ${time}`);}
function setFooterStatus(online){["haStatus","shellyStatus","marstekStatus"].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.toggle("offline",!online);});}
function setWeather(data){const sky=document.getElementById("skyBody"),icon=document.getElementById("weatherIcon"),a=document.getElementById("cloudA"),b=document.getElementById("cloudB");sky.classList.toggle("moon",!!data.night);const cloudy=(data.weather==="cloudy"||data.weather==="rain")&&!data.night;a.classList.toggle("hidden",!cloudy);b.classList.toggle("hidden",!cloudy);icon.innerText=data.night?"🌙":data.weather==="rain"?"🌧":data.weather==="cloudy"?"🌤":"☀";}
function setStatus(fromGrid){const cfg=window.WZ_CONFIG,box=document.getElementById("statusBox"),icon=document.getElementById("statusIcon");if(fromGrid>cfg.autarkThresholdW){box.classList.add("grid-active");icon.innerText="!";text("autarkStatus","NETZBEZUG");text("statusSmall",`${fmt(fromGrid)} W aus dem Netz`);}else{box.classList.remove("grid-active");icon.innerText="✓";text("autarkStatus","AUTARK");text("statusSmall","Netzbezug unter 20 W");}}
function setAssistant(data,fromGrid,fromBattery){const cfg=window.WZ_CONFIG;if(fromGrid>cfg.autarkThresholdW){html("assistantText",`🔴 Das öffentliche Netz ergänzt <span class="red-word">${fmt(fromGrid)} W</span>. Der Speicher liefert <span class="green-word">${fmt(fromBattery)} W</span> direkt an die Wohnung.`);}else if(data.pvPower>10&&data.batteryChargePower>20){html("assistantText",`☀ Die <span class="yellow-word">Sonne</span> lädt den <span class="green-word">Speicher</span> mit ${fmt(data.pvPower)} W.`);}else if(data.night){html("assistantText",`🌙 Nachtbetrieb: Der <span class="green-word">Speicher</span> versorgt die Wohnung.`);}else{html("assistantText",`🔋 Der <span class="green-word">Speicher</span> versorgt die Wohnung.`);}}
function setTip(data,fromGrid){if(fromGrid>20)html("aiTip",`💡 <b>KI-Empfehlung:</b> Momentan Netzbezug. Größere Verbraucher nach Möglichkeit verschieben.`);else if(data.pvPower>1000&&data.batterySoc<95)html("aiTip",`💡 <b>KI-Empfehlung:</b> Hohe PV-Leistung – Waschmaschine oder Geschirrspüler jetzt günstig.`);else if(data.batterySoc<25)html("aiTip",`💡 <b>KI-Empfehlung:</b> Speicher nahe Reserve. Größere Verbraucher vermeiden.`);else html("aiTip",`💡 <b>KI-Empfehlung:</b> System läuft stabil. Die Wohnung wird weitgehend selbst versorgt.`);}
function updateDashboard(data,online=false){const cfg=window.WZ_CONFIG;const homeLoad=Math.max(Number(data.homeLoad)||0,0);const fromGrid=Math.max(Number(data.gridPower)||0,0);const fromBattery=Math.min(Math.max(homeLoad-fromGrid,0),cfg.maxBatteryOutputW);const batteryKwh=cfg.batteryCapacityKwh*(Number(data.batterySoc)||0)/100;const batteryPercent=homeLoad>0?fromBattery/homeLoad*100:0;const gridPercent=homeLoad>0?fromGrid/homeLoad*100:0;text("pvPower",`${fmt(data.pvPower)} W`);text("batterySoc",`${fmt(data.batterySoc)} %`);text("batteryKwh",`${fmt(batteryKwh,2)} kWh`);text("batteryState",data.pvPower>10?`Lädt mit ${fmt(data.batteryChargePower)} W`:"Versorgt Wohnung");text("homeLoad",`${fmt(homeLoad)} W`);text("gridPower",`${fmt(fromGrid)} W`);text("fromBattery",`${fmt(fromBattery)} W`);text("fromGrid",`${fmt(fromGrid)} W`);text("fromBatteryPercent",`${fmt(batteryPercent)} %`);text("fromGridPercent",`${fmt(gridPercent)} %`);text("savingToday",euro(data.batteryDailyKwh*cfg.pricePerKwh));text("savingMonth",euro(data.batteryMonthKwh*cfg.pricePerKwh));text("savingTotal",euro(data.batteryTotalKwh*cfg.pricePerKwh));const ringDeg=Math.max(0,Math.min(360,Math.round((Number(data.batterySoc)||0)*3.6)));document.getElementById("batteryRing").style.background=`conic-gradient(#57ff4b 0deg ${ringDeg}deg, rgba(255,255,255,.12) ${ringDeg}deg 360deg)`;const donutDeg=Math.max(0,Math.min(360,Math.round(batteryPercent*3.6)));document.getElementById("donut").style.background=`conic-gradient(#6dff4b 0deg ${donutDeg}deg, #ff4545 ${donutDeg}deg 360deg)`;document.getElementById("greenBar").style.width=`${Math.max(0,Math.min(100,batteryPercent))}%`;document.getElementById("redBar").style.width=`${Math.max(0,Math.min(100,gridPercent))}%`;document.getElementById("gridFlow").classList.toggle("active",fromGrid>cfg.autarkThresholdW);document.getElementById("pvFlow").classList.toggle("inactive",data.pvPower<=10);document.getElementById("batteryFlow").classList.toggle("inactive",fromBattery<=10);setStatus(fromGrid);setAssistant(data,fromGrid,fromBattery);setTip(data,fromGrid);setWeather(data);setFooterStatus(online);}
async function loadData(){const cfg=window.WZ_CONFIG;try{const states=await window.WZ_HA.getStates();if(!states){updateDashboard(demo,false);return;}const e=cfg.entities;const live={pvPower:WZ_HA.num(states,e.pvPower,demo.pvPower),batterySoc:WZ_HA.num(states,e.batterySoc,demo.batterySoc),batteryChargePower:WZ_HA.num(states,e.batteryChargePower,demo.batteryChargePower),homeLoad:Math.abs(WZ_HA.num(states,e.homeLoad,demo.homeLoad)),gridPower:Math.max(WZ_HA.num(states,e.gridPower,demo.gridPower),0),batteryDailyKwh:WZ_HA.num(states,e.batteryDailyKwh,demo.batteryDailyKwh),batteryMonthKwh:WZ_HA.num(states,e.batteryMonthKwh,demo.batteryMonthKwh),batteryTotalKwh:WZ_HA.num(states,e.batteryTotalKwh,demo.batteryTotalKwh),weather:"cloudy",night:false};updateDashboard(live,true);}catch(err){console.error(err);updateDashboard(demo,false);}}
document.addEventListener("touchmove",e=>e.preventDefault(),{passive:false});document.addEventListener("gesturestart",e=>e.preventDefault());document.addEventListener("dblclick",e=>e.preventDefault());updateTime();loadData();setInterval(updateTime,1000);setInterval(loadData,3000);
